### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/api/v1/courses/1/create
Content-Type: application/json

{
  "description": "This comprehensive python course that teaches you python programming language from basics to advanced level",
  "title": "python for beginners",
  "price": 0
}
###
PUT http://localhost:8080/api/v1/courses/2/enroll/1
###
PUT http://localhost:8080/api/v1/courses/2/un-enroll/1