### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/api/v1/courses/1/create
Content-Type: application/json

{
  "description": "This comprehensive Software Engineering course that teaches you SOftware engineering concepts from basics to advanced level",
  "title": "Software Engineering",
  "price": 0
}
###
PUT http://localhost:8080/api/v1/courses/2/enroll/1
###
PUT http://localhost:8080/api/v1/courses/2/un-enroll/1

###
GET http://localhost:8080/api/v1/courses/all
###
GET http://localhost:8080/api/v1/courses/1/get
###
GET http://localhost:8080/api/v1/courses/course-map